-- AMD 데스크톱 CPU 시드 (AM4/AM5)
-- generated by scripts/generate_amd_seed.py — 직접 수정하지 말 것
-- source: datasource/AMD_Processor_Specifications.csv, 247 rows

USE parts_catalog;

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen AI 7 PRO 450GE', 'AMD Ryzen™ AI 7 PRO 450GE', 2026);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 8, 16, 2000, 5100, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen AI 7 PRO 450G', 'AMD Ryzen™ AI 7 PRO 450G', 2026);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 8, 16, 2000, 5100, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen AI 5 PRO 440GE', 'AMD Ryzen™ AI 5 PRO 440GE', 2026);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 6, 12, 2000, 4800, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen AI 5 PRO 440G', 'AMD Ryzen™ AI 5 PRO 440G', 2026);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 6, 12, 2000, 4800, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen AI 5 PRO 435GE', 'AMD Ryzen™ AI 5 PRO 435GE', 2026);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 6, 12, 2000, 4500, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen AI 5 PRO 435G', 'AMD Ryzen™ AI 5 PRO 435G', 2026);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 6, 12, 2000, 4500, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen AI 7 450GE', 'AMD Ryzen™ AI 7 450GE', NULL);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 8, 16, 2000, 5100, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen AI 7 450G', 'AMD Ryzen™ AI 7 450G', NULL);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 8, 16, 2000, 5100, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen AI 5 440GE', 'AMD Ryzen™ AI 5 440GE', NULL);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 6, 12, 2000, 4800, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen AI 5 440G', 'AMD Ryzen™ AI 5 440G', NULL);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 6, 12, 2000, 4800, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen AI 5 435GE', 'AMD Ryzen™ AI 5 435GE', NULL);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 6, 12, 2000, 4500, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen AI 5 435G', 'AMD Ryzen™ AI 5 435G', NULL);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 6, 12, 2000, 4500, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 9 PRO 9965X3D', 'AMD Ryzen™ 9 PRO 9965X3D', 2026);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 16, 32, 4300, 5500, 170, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 9 PRO 9965', 'AMD Ryzen™ 9 PRO 9965', 2026);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 16, 32, 4300, 5500, 170, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 9 PRO 9955', 'AMD Ryzen™ 9 PRO 9955', 2026);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 12, 24, 3400, 5400, 120, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 9 PRO 9945', 'AMD Ryzen™ 9 PRO 9945', 2025);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 12, 24, 3400, 5400, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 PRO 9755X3D', 'AMD Ryzen™ 7 PRO 9755X3D', 2026);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 8, 16, 4700, 5200, 120, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 PRO 9755', 'AMD Ryzen™ 7 PRO 9755', 2026);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 8, 16, 3800, 5400, 120, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 PRO 9745', 'AMD Ryzen™ 7 PRO 9745', 2025);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 8, 16, 3800, 5400, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 PRO 9655', 'AMD Ryzen™ 5 PRO 9655', 2026);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 6, 12, 3900, 5400, 120, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 PRO 9645', 'AMD Ryzen™ 5 PRO 9645', 2025);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 6, 12, 3900, 5400, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 9 9950X3D2 Dual Edition', 'AMD Ryzen™ 9 9950X3D2 Dual Edition', NULL);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 16, 32, 4300, 5600, 200, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 9 9950X3D', 'AMD Ryzen™ 9 9950X3D', 2025);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 16, 32, 4300, 5700, 170, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 9 9950X', 'AMD Ryzen™ 9 9950X', 2024);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 16, 32, 4300, 5700, 170, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 9 9900X3D', 'AMD Ryzen™ 9 9900X3D', 2025);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 12, 24, 4400, 5500, 120, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 9 9900X', 'AMD Ryzen™ 9 9900X', 2024);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 12, 24, 4400, 5600, 120, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 9850X3D', 'AMD Ryzen™ 7 9850X3D', 2026);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 8, 16, 4700, 5600, 120, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 9800X3D', 'AMD Ryzen™ 7 9800X3D', 2024);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 8, 16, 4700, 5200, 120, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 9700X', 'AMD Ryzen™ 7 9700X', 2024);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 8, 16, 3800, 5500, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 9700F', 'AMD Ryzen™ 7 9700F', NULL);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 8, 16, 3800, 5500, 65, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 9600X', 'AMD Ryzen™ 5 9600X', 2024);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 6, 12, 3900, 5400, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 9600', 'AMD Ryzen™ 5 9600', 2025);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 6, 12, 3800, 5200, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 9500F', 'AMD Ryzen™ 5 9500F', NULL);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 6, 12, 3800, 5000, 65, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 PRO 8705GE', 'AMD Ryzen™ 7 PRO 8705GE', 2025);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 8, 16, 3600, 5100, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 PRO 8705G', 'AMD Ryzen™ 7 PRO 8705G', 2025);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 8, 16, 4200, 5100, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 PRO 8700GE', 'AMD Ryzen™ 7 PRO 8700GE', 2024);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 8, 16, 3600, 5100, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 PRO 8700G', 'AMD Ryzen™ 7 PRO 8700G', 2024);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 8, 16, 4200, 5100, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 PRO 8605GE', 'AMD Ryzen™ 5 PRO 8605GE', 2025);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 6, 12, 3900, 5000, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 PRO 8605G', 'AMD Ryzen™ 5 PRO 8605G', 2025);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 6, 12, 4300, 5000, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 PRO 8600GE', 'AMD Ryzen™ 5 PRO 8600GE', 2024);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 6, 12, 3900, 5000, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 PRO 8600G', 'AMD Ryzen™ 5 PRO 8600G', 2024);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 6, 12, 4300, 5000, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 PRO 8505GE', 'AMD Ryzen™ 5 PRO 8505GE', 2025);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 6, 12, 3400, 5000, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 PRO 8505G', 'AMD Ryzen™ 5 PRO 8505G', 2025);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 6, 12, 3500, 5000, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 PRO 8500GE', 'AMD Ryzen™ 5 PRO 8500GE', 2024);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 6, 12, 3400, 5000, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 PRO 8500G', 'AMD Ryzen™ 5 PRO 8500G', 2024);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 6, 12, 3500, 5000, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 3 PRO 8305GE', 'AMD Ryzen™ 3 PRO 8305GE', 2025);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 4, 8, 3500, 4900, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 3 PRO 8305G', 'AMD Ryzen™ 3 PRO 8305G', 2025);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 4, 8, 3400, 4900, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 3 PRO 8300GE', 'AMD Ryzen™ 3 PRO 8300GE', 2024);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 4, 8, 3500, 4900, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 3 PRO 8300G', 'AMD Ryzen™ 3 PRO 8300G', 2024);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 4, 8, 3400, 4900, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 8705G', 'AMD Ryzen™ 7 8705G', 2025);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 8, 16, 4200, 5100, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 8700G', 'AMD Ryzen™ 7 8700G', 2024);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 8, 16, 4200, 5100, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 8700F', 'AMD Ryzen™ 7 8700F', 2024);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 8, 16, 4100, 5000, 65, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 8605G', 'AMD Ryzen™ 5 8605G', 2025);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 6, 12, 4300, 5000, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 8600G', 'AMD Ryzen™ 5 8600G', 2024);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 6, 12, 4300, 5000, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 8505GE', 'AMD Ryzen™ 5 8505GE', 2025);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 6, 12, 3400, 5000, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 8505G', 'AMD Ryzen™ 5 8505G', 2025);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 6, 12, 3500, 5000, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 8500GE', 'AMD Ryzen™ 5 8500GE', 2024);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 6, 12, 3400, 5000, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 8500G', 'AMD Ryzen™ 5 8500G', 2024);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 6, 12, 3500, 5000, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 8400F', 'AMD Ryzen™ 5 8400F', 2024);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 6, 12, 4200, 4700, 65, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 3 8305GE', 'AMD Ryzen™ 3 8305GE', 2025);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 4, 8, 3500, 4900, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 3 8305G', 'AMD Ryzen™ 3 8305G', 2025);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 4, 8, 3400, 4900, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 3 8300GE', 'AMD Ryzen™ 3 8300GE', 2024);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 4, 8, 3500, 4900, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 3 8300G', 'AMD Ryzen™ 3 8300G', 2024);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 4, 8, 3400, 4900, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 9 PRO 7945', 'AMD Ryzen™ 9 PRO 7945', 2023);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 12, 24, 3700, 5400, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 PRO 7745', 'AMD Ryzen™ 7 PRO 7745', 2023);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 8, 16, 3800, 5300, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 PRO 7645', 'AMD Ryzen™ 5 PRO 7645', 2023);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 6, 12, 3800, 5100, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 PRO 7445', 'AMD Ryzen™ 5 PRO 7445', 2025);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 6, 12, 3300, 4300, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 9 7950X3D', 'AMD Ryzen™ 9 7950X3D', 2023);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 16, 32, 4200, 5700, 120, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 9 7950X', 'AMD Ryzen™ 9 7950X', 2022);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 16, 32, 4500, 5700, 170, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 9 7900X3D', 'AMD Ryzen™ 9 7900X3D', 2023);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 12, 24, 4400, 5600, 120, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 9 7900X', 'AMD Ryzen™ 9 7900X', 2022);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 12, 24, 4700, 5600, 170, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 9 7900', 'AMD Ryzen™ 9 7900', 2023);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 12, 24, 3700, 5400, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 7800X3D', 'AMD Ryzen™ 7 7800X3D', 2023);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 8, 16, 4200, 5000, 120, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 7700X3D', 'AMD Ryzen™ 7 7700X3D', NULL);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 8, 16, 4000, 4500, 120, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 7700X', 'AMD Ryzen™ 7 7700X', 2022);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 8, 16, 4500, 5400, 105, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 7700', 'AMD Ryzen™ 7 7700', 2023);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 8, 16, 3800, 5300, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 7600X3D', 'AMD Ryzen™ 5 7600X3D', 2024);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 6, 12, 4100, 4700, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 7600X', 'AMD Ryzen™ 5 7600X', 2022);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 6, 12, 4700, 5300, 105, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 7600', 'AMD Ryzen™ 5 7600', 2023);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 6, 12, 3800, 5100, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 7500X3D', 'AMD Ryzen™ 5 7500X3D', 2025);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 6, 12, 4000, 4500, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 7500F', 'AMD Ryzen™ 5 7500F', 2023);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 6, 12, 3700, 5000, 65, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 7400F', 'AMD Ryzen™ 5 7400F', 2025);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 6, 12, 3700, 4700, 65, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 7400', 'AMD Ryzen™ 5 7400', NULL);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM5', 6, 12, 3300, 4300, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 9 PRO 5945', 'AMD Ryzen™ 9 PRO 5945', NULL);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 12, 24, 3000, 4700, 65, NULL);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 PRO 5845', 'AMD Ryzen™ 7 PRO 5845', NULL);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 8, 16, 3400, 4600, 65, NULL);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 PRO 5755GE', 'AMD Ryzen™ 7 PRO 5755GE', 2024);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 8, 16, 3200, 4600, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 PRO 5755G', 'AMD Ryzen™ 7 PRO 5755G', 2024);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 8, 16, 3800, 4600, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 PRO 5750GE', 'AMD Ryzen™ 7 PRO 5750GE', 2021);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 8, 16, 3200, 4600, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 PRO 5750G', 'AMD Ryzen™ 7 PRO 5750G', 2021);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 8, 16, 3800, 4600, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 PRO 5655GE', 'AMD Ryzen™ 5 PRO 5655GE', 2024);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 6, 12, 3400, 4400, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 PRO 5655G', 'AMD Ryzen™ 5 PRO 5655G', 2024);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 6, 12, 3900, 4400, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 PRO 5650GE', 'AMD Ryzen™ 5 PRO 5650GE', 2021);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 6, 12, 3400, 4400, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 PRO 5650G', 'AMD Ryzen™ 5 PRO 5650G', 2021);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 6, 12, 3900, 4400, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 PRO 5645', 'AMD Ryzen™ 5 PRO 5645', NULL);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 6, 12, 3700, 4600, 65, NULL);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 3 PRO 5355GE', 'AMD Ryzen™ 3 PRO 5355GE', 2024);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 8, 3600, 4200, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 3 PRO 5355G', 'AMD Ryzen™ 3 PRO 5355G', 2024);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 8, 4000, 4200, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 3 PRO 5350GE', 'AMD Ryzen™ 3 PRO 5350GE', 2021);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 8, 3600, 4200, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 3 PRO 5350G', 'AMD Ryzen™ 3 PRO 5350G', 2021);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 8, 4000, 4200, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 9 5950X', 'AMD Ryzen™ 9 5950X', 2020);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 16, 32, 3400, 4900, 105, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 9 5900XT', 'AMD Ryzen™ 9 5900XT', 2024);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 16, 32, 3300, 4800, 105, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 9 5900X', 'AMD Ryzen™ 9 5900X', 2020);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 12, 24, 3700, 4800, 105, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 9 5900 (OEM Only)', 'AMD Ryzen™ 9 5900 (OEM Only)', 2021);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 12, 24, 3000, 4700, 65, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 5800X3D', 'AMD Ryzen™ 7 5800X3D', 2022);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 8, 16, 3400, 4500, 105, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 5800XT', 'AMD Ryzen™ 7 5800XT', 2024);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 8, 16, 3800, 4800, 105, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 5800X', 'AMD Ryzen™ 7 5800X', 2020);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 8, 16, 3800, 4700, 105, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 5800 (OEM Only)', 'AMD Ryzen™ 7 5800 (OEM Only)', 2021);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 8, 16, 3400, 4600, 65, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 5705GE', 'AMD Ryzen™ 7 5705GE', NULL);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 8, 16, 3200, 4600, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 5705G', 'AMD Ryzen™ 7 5705G', NULL);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 8, 16, 3800, 4600, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 5700X3D', 'AMD Ryzen™ 7 5700X3D', 2024);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 8, 16, 3000, 4100, 105, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 5700X', 'AMD Ryzen™ 7 5700X', 2022);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 8, 16, 3400, 4600, 65, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 5700GE', 'AMD Ryzen™ 7 5700GE', 2021);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 8, 16, 3200, 4600, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 5700G', 'AMD Ryzen™ 7 5700G', 2021);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 8, 16, 3800, 4600, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 5700', 'AMD Ryzen™ 7 5700', 2024);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 8, 16, 3700, 4600, 65, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 5605GE', 'AMD Ryzen™ 5 5605GE', NULL);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 6, 12, 3400, 4400, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 5605G', 'AMD Ryzen™ 5 5605G', NULL);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 6, 12, 3900, 4400, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 5600X3D', 'AMD Ryzen™ 5 5600X3D', 2023);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 6, 12, 3300, 4400, 105, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 5600X', 'AMD Ryzen™ 5 5600X', 2020);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 6, 12, 3700, 4600, 65, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 5600XT', 'AMD Ryzen™ 5 5600XT', 2024);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 6, 12, 3700, 4700, 65, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 5600T', 'AMD Ryzen™ 5 5600T', 2024);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 6, 12, 3500, 4500, 65, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 5600GT', 'AMD Ryzen™ 5 5600GT', 2024);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 6, 12, 3600, 4600, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 5600GE', 'AMD Ryzen™ 5 5600GE', 2021);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 6, 12, 3400, 4400, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 5600G', 'AMD Ryzen™ 5 5600G', 2021);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 6, 12, 3900, 4400, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 5600F', 'AMD Ryzen™ 5 5600F', NULL);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 6, 12, 3000, 4000, 65, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 5600', 'AMD Ryzen™ 5 5600', 2022);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 6, 12, 3500, 4400, 65, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 5500X3D', 'AMD Ryzen™ 5 5500X3D', 2025);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 6, 12, 3000, 4000, 105, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 5500GT', 'AMD Ryzen™ 5 5500GT', 2024);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 6, 12, 3600, 4400, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 5500', 'AMD Ryzen™ 5 5500', 2022);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 6, 12, 3600, 4200, 65, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 3 5305GE', 'AMD Ryzen™ 3 5305GE', NULL);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 8, 3600, 4200, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 3 5305G', 'AMD Ryzen™ 3 5305G', NULL);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 8, 4000, 4200, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 3 5300GE (OEM Only)', 'AMD Ryzen™ 3 5300GE (OEM Only)', 2021);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 8, 3600, 4200, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 3 5300G (OEM Only)', 'AMD Ryzen™ 3 5300G (OEM Only)', 2021);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 8, 4000, 4200, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 PRO 4750GE', 'AMD Ryzen™ 7 PRO 4750GE', 2020);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 8, 16, 3100, 4300, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 PRO 4750G', 'AMD Ryzen™ 7 PRO 4750G', 2020);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 8, 16, 3600, 4400, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 PRO 4655GE', 'AMD Ryzen™ 5 PRO 4655GE', 2022);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 6, 12, 3300, 4200, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 PRO 4655G', 'AMD Ryzen™ 5 PRO 4655G', 2022);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 6, 12, 3700, 4200, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 PRO 4650GE', 'AMD Ryzen™ 5 PRO 4650GE', 2020);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 6, 12, 3300, 4200, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 PRO 4650G', 'AMD Ryzen™ 5 PRO 4650G', 2020);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 6, 12, 3700, 4200, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 3 PRO 4355GE', 'AMD Ryzen™ 3 PRO 4355GE', 2022);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 8, 3500, 4000, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 3 PRO 4355G', 'AMD Ryzen™ 3 PRO 4355G', 2022);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 8, 3800, 4000, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 3 PRO 4350GE', 'AMD Ryzen™ 3 PRO 4350GE', 2020);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 8, 3500, 4000, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 3 PRO 4350G', 'AMD Ryzen™ 3 PRO 4350G', 2020);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 8, 3800, 4000, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 4700GE (OEM Only)', 'AMD Ryzen™ 7 4700GE (OEM Only)', 2020);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 8, 16, 3100, 4300, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 4700G (OEM Only)', 'AMD Ryzen™ 7 4700G (OEM Only)', 2020);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 8, 16, 3600, 4400, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 4600GE (OEM Only)', 'AMD Ryzen™ 5 4600GE (OEM Only)', 2020);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 6, 12, 3300, 4200, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 4600G', 'AMD Ryzen™ 5 4600G', 2020);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 6, 12, 3700, 4200, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 4500', 'AMD Ryzen™ 5 4500', 2022);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 6, 12, 3600, 4100, 65, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 3 4300GE (OEM Only)', 'AMD Ryzen™ 3 4300GE (OEM Only)', 2020);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 8, 3500, 4000, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 3 4300G (OEM Only)', 'AMD Ryzen™ 3 4300G (OEM Only)', 2020);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 8, 3800, 4000, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 3 4100', 'AMD Ryzen™ 3 4100', 2022);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 8, 3800, 4000, 65, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 9 PRO 3900', 'AMD Ryzen™ 9 PRO 3900', 2019);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 12, 24, 3100, 4300, 65, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 PRO 3700', 'AMD Ryzen™ 7 PRO 3700', 2019);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 8, 16, 3600, 4400, 65, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 PRO 3600', 'AMD Ryzen™ 5 PRO 3600', 2019);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 6, 12, 3600, 4200, 65, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 PRO 3400GE', 'AMD Ryzen™ 5 PRO 3400GE', 2019);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 8, 3300, 4000, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 PRO 3400G', 'AMD Ryzen™ 5 PRO 3400G', 2019);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 8, 3700, 4200, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 PRO 3350G', 'AMD Ryzen™ 5 PRO 3350G', 2020);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 8, 3600, 4000, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 3 PRO 3200GE', 'AMD Ryzen™ 3 PRO 3200GE', 2019);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 4, 3300, 3800, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 3 PRO 3200G', 'AMD Ryzen™ 3 PRO 3200G', 2019);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 4, 3600, 4000, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 9 3950X', 'AMD Ryzen™ 9 3950X', 2019);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 16, 32, 3500, 4700, 105, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 9 3900X', 'AMD Ryzen™ 9 3900X', 2019);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 12, 24, 3800, 4600, 105, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 9 3900 Processor (OEM Only)', 'AMD Ryzen™ 9 3900 Processor (OEM Only)', 2019);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 12, 24, 3100, 4300, 65, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 3800XT', 'AMD Ryzen™ 7 3800XT', 2020);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 8, 16, 3900, 4700, 105, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 3800X', 'AMD Ryzen™ 7 3800X', 2019);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 8, 16, 3900, 4500, 105, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 3700X', 'AMD Ryzen™ 7 3700X', 2019);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 8, 16, 3600, 4400, 65, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 3600XT', 'AMD Ryzen™ 5 3600XT', 2020);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 6, 12, 3800, 4500, 95, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 3600X', 'AMD Ryzen™ 5 3600X', 2019);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 6, 12, 3800, 4400, 95, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 3600', 'AMD Ryzen™ 5 3600', 2019);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 6, 12, 3600, 4200, 65, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 3500 Processor (OEM Only)', 'AMD Ryzen™ 5 3500 Processor (OEM Only)', NULL);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 6, 6, 3600, 4100, 65, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 3400GE (OEM Only)', 'AMD Ryzen™ 5 3400GE (OEM Only)', 2019);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 8, 3300, 4000, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 3400G with Radeon RX Vega 11 Graphics', 'AMD Ryzen™ 5 3400G with Radeon™ RX Vega 11 Graphics', 2019);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 8, 3700, 4200, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 3 3300X', 'AMD Ryzen™ 3 3300X', NULL);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 8, 3800, 4300, 65, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 3 3200GE (OEM Only)', 'AMD Ryzen™ 3 3200GE (OEM Only)', 2019);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 4, 3300, 3800, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 3 3200G with Radeon Vega 8 Graphics', 'AMD Ryzen™ 3 3200G with Radeon™ Vega 8 Graphics', 2019);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 4, 3600, 4000, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 3 3100', 'AMD Ryzen™ 3 3100', 2020);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 8, 3600, 3900, 65, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Athlon Gold PRO 3150GE', 'AMD Athlon™ Gold PRO 3150GE', 2020);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 4, 3300, 3800, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Athlon Gold PRO 3150G', 'AMD Athlon™ Gold PRO 3150G', 2020);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 4, 3500, 3900, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Athlon Silver PRO 3125GE', 'AMD Athlon™ Silver PRO 3125GE', 2020);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 2, 4, 3400, 3400, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Athlon Gold 3150GE (OEM Only)', 'AMD Athlon™ Gold 3150GE (OEM Only)', 2020);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 4, 3300, 3800, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Athlon Gold 3150G (OEM Only)', 'AMD Athlon™ Gold 3150G (OEM Only)', 2020);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 4, 3500, 3900, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Athlon Silver 3050GE (OEM Only)', 'AMD Athlon™ Silver 3050GE (OEM Only)', 2020);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 2, 4, 3400, 3400, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Athlon 3000G', 'AMD Athlon™ 3000G', NULL);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 2, 4, 3500, NULL, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Athlon PRO 300GE', 'AMD Athlon™ PRO 300GE', 2019);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 2, 4, 3400, NULL, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Athlon 320GE', 'AMD Athlon™ 320GE', 2019);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 2, 4, 3500, NULL, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Athlon 300GE', 'AMD Athlon™ 300GE', 2019);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 2, 4, 3400, NULL, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Athlon PRO 200GE', 'AMD Athlon™ PRO 200GE', NULL);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 2, 4, 3200, NULL, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Athlon 240GE', 'AMD Athlon™ 240GE', NULL);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 2, 4, 3500, NULL, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Athlon 220GE', 'AMD Athlon™ 220GE', NULL);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 2, 4, 3400, NULL, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Athlon 200GE', 'AMD Athlon™ 200GE', NULL);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 2, 4, 3200, NULL, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 PRO 2700X', 'AMD Ryzen™ 7 PRO 2700X', NULL);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 8, 16, 3600, 4100, 95, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 PRO 2700', 'AMD Ryzen™ 7 PRO 2700', NULL);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 8, 16, 3200, 4100, 65, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 PRO 2600', 'AMD Ryzen™ 5 PRO 2600', NULL);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 6, 12, 3400, 3900, 65, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 PRO 2400GE with Radeon Vega 11 Graphics', 'AMD Ryzen™ 5 PRO 2400GE with Radeon™ Vega 11 Graphics', 2018);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 8, 3200, 3800, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 PRO 2400G with Radeon Vega 11 Graphics', 'AMD Ryzen™ 5 PRO 2400G with Radeon™ Vega 11 Graphics', 2018);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 8, 3600, 3900, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 3 PRO 2200GE with Radeon Vega 8 Graphics', 'AMD Ryzen™ 3 PRO 2200GE with Radeon™ Vega 8 Graphics', 2018);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 4, 3200, 3600, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 3 PRO 2200G with Radeon Vega 8 Graphics', 'AMD Ryzen™ 3 PRO 2200G with Radeon™ Vega 8 Graphics', 2018);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 4, 3500, 3700, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 2700X', 'AMD Ryzen™ 7 2700X', 2018);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 8, 16, 3700, 4300, 105, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 2700E Processor', 'AMD Ryzen™ 7 2700E Processor', 2018);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 8, 16, 2800, 4000, 45, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 2700', 'AMD Ryzen™ 7 2700', 2018);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 8, 16, 3200, 4100, 65, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 2600X', 'AMD Ryzen™ 5 2600X', 2018);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 6, 12, 3600, 4200, 95, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 2600E', 'AMD Ryzen™ 5 2600E', 2018);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 6, 12, 3100, 4000, 45, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 2600', 'AMD Ryzen™ 5 2600', 2018);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 6, 12, 3400, 3900, 65, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 2500X', 'AMD Ryzen™ 5 2500X', 2018);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 8, 3600, 4000, 65, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 2400GE with Radeon RX Vega 11 Graphics', 'AMD Ryzen™ 5 2400GE with Radeon™ RX Vega 11 Graphics', 2018);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 8, 3200, 3800, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 2400G with Radeon RX Vega 11 Graphics', 'AMD Ryzen™ 5 2400G with Radeon™ RX Vega 11 Graphics', 2018);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 8, 3600, 3900, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 3 2300X', 'AMD Ryzen™ 3 2300X', 2018);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 4, 3500, 4000, 65, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 3 2200GE with Radeon Vega 8 Graphics', 'AMD Ryzen™ 3 2200GE with Radeon™ Vega 8 Graphics', 2018);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 4, 3200, 3600, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 3 2200G with Radeon Vega 8 Graphics', 'AMD Ryzen™ 3 2200G with Radeon™ Vega 8 Graphics', 2018);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 4, 3500, 3700, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 PRO 1700X Processor', 'AMD Ryzen™ 7 PRO 1700X Processor', 2017);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 8, 16, 3400, 3800, 95, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 PRO 1700', 'AMD Ryzen™ 7 PRO 1700', 2017);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 8, 16, 3000, 3700, 65, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 PRO 1600', 'AMD Ryzen™ 5 PRO 1600', 2017);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 6, 12, 3200, 3600, 65, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 PRO 1500', 'AMD Ryzen™ 5 PRO 1500', 2017);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 8, 3500, 3700, 65, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 3 PRO 1300', 'AMD Ryzen™ 3 PRO 1300', 2017);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 4, 3500, 3700, 65, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 3 PRO 1200', 'AMD Ryzen™ 3 PRO 1200', 2017);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 4, 3100, 3400, 65, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 1800X', 'AMD Ryzen™ 7 1800X', 2017);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 8, 16, 3600, 4000, 95, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 1700X', 'AMD Ryzen™ 7 1700X', 2017);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 8, 16, 3400, 3800, 95, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 1700 Processor', 'AMD Ryzen™ 7 1700 Processor', 2017);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 8, 16, 3000, 3700, 65, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 1600X', 'AMD Ryzen™ 5 1600X', 2017);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 6, 12, 3600, 4000, 95, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 1600 (AF)', 'AMD Ryzen™ 5 1600 (AF)', NULL);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 6, 12, 3200, 3600, 65, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 1600', 'AMD Ryzen™ 5 1600', 2017);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 6, 12, 3200, 3600, 65, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 1500X', 'AMD Ryzen™ 5 1500X', 2017);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 8, 3500, 3700, 65, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 5 1400', 'AMD Ryzen™ 5 1400', 2017);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 8, 3200, 3400, 65, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 3 1300X', 'AMD Ryzen™ 3 1300X', 2017);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 4, 3500, 3700, 65, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 3 1200', 'AMD Ryzen™ 3 1200', 2017);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 4, 3100, 3400, 65, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', '7th Gen A12-9800E APU', '7th Gen A12-9800E APU', 2016);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, NULL, 3100, 3800, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', '7th Gen A12-9800 APU', '7th Gen A12-9800 APU', 2017);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, NULL, 3800, 4200, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', '7th Gen AMD PRO A12-9800E APU', '7th Gen AMD PRO A12-9800E APU', 2016);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, NULL, 3100, 3800, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', '7th Gen AMD PRO A12-9800 APU', '7th Gen AMD PRO A12-9800 APU', 2016);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, NULL, 3800, 4200, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', '6th Gen AMD PRO A12-8870E APU', '6th Gen AMD PRO A12-8870E APU', NULL);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, NULL, 2900, 3800, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', '6th Gen AMD PRO A12-8870 APU', '6th Gen AMD PRO A12-8870 APU', 2016);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, NULL, 3700, 4200, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', '7th Gen A10-9700E APU', '7th Gen A10-9700E APU', 2016);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, NULL, 3000, 3500, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', '7th Gen A10-9700 APU', '7th Gen A10-9700 APU', 2017);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, NULL, 3500, 3800, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', '7th Gen AMD PRO A10-9700E APU', '7th Gen AMD PRO A10-9700E APU', 2016);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, NULL, 3000, 3500, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', '7th Gen AMD PRO A10-9700 APU', '7th Gen AMD PRO A10-9700 APU', 2016);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, NULL, 3500, 3800, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', '6th Gen AMD PRO A10-8770E APU', '6th Gen AMD PRO A10-8770E APU', 2016);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, NULL, 2800, 3500, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', '6th Gen AMD PRO A10-8770 APU', '6th Gen AMD PRO A10-8770 APU', 2016);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, NULL, 3500, 3800, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', '7th Gen A8-9600 APU', '7th Gen A8-9600 APU', 2017);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, NULL, 3100, 3400, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', '7th Gen AMD PRO A8-9600 APU', '7th Gen AMD PRO A8-9600 APU', 2016);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, NULL, 3100, 3400, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', '7th Gen A6-9550 APU', '7th Gen A6-9550 APU', 2017);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 2, NULL, 3800, 4000, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', '7th Gen A6-9500E APU', '7th Gen A6-9500E APU', 2017);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 2, NULL, 3000, 3400, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', '7th Gen A6-9500 APU', '7th Gen A6-9500 APU', 2017);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 2, NULL, 3500, 3800, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', '7th Gen AMD PRO A6-9500E APU', '7th Gen AMD PRO A6-9500E APU', 2016);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 2, NULL, 3000, 3400, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', '7th Gen AMD PRO A6-9500 APU', '7th Gen AMD PRO A6-9500 APU', 2016);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 2, NULL, 3500, 3800, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', '6th Gen AMD PRO A6-8570E APU', '6th Gen AMD PRO A6-8570E APU', NULL);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 2, NULL, 3000, 3400, 35, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', '6th Gen AMD PRO A6-8570 APU', '6th Gen AMD PRO A6-8570 APU', NULL);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 2, NULL, 3500, 3800, 65, TRUE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', '7th Gen AMD Athlon X4 970', '7th Gen AMD Athlon™ X4 970', 2017);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 4, 3800, 4000, 65, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', '7th Gen AMD Athlon X4 950', '7th Gen AMD Athlon™ X4 950', 2017);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 4, 3500, 3800, NULL, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', '7th Gen AMD Athlon X4 940', '7th Gen AMD Athlon™ X4 940', 2017);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 4, 4, 3200, 3600, NULL, FALSE);

INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)
VALUES ('CPU', 'AMD', 'Ryzen 7 4700LE (OEM Only)', 'AMD Ryzen™ 7 4700LE (OEM Only)', 2026);
INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)
VALUES (LAST_INSERT_ID(), 'AM4', 8, 16, 3600, 4200, 65, FALSE);
