"""AMD 공식 스펙 CSV → db/seed/amd_cpu_seed.sql 생성.

재실행 가능한 파이프라인: AMD가 CSV를 갱신하면 datasource/에 덮어쓰고
이 스크립트를 다시 돌리면 시드 SQL이 재생성된다.

사용법:
    python scripts/generate_amd_seed.py            # SQL 생성
    python scripts/generate_amd_seed.py --verify   # 생성 후 SQLite 인메모리 적재 검증
"""

import csv
import re
import sqlite3
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CSV_PATH = ROOT / "datasource" / "AMD_Processor_Specifications.csv"
OUT_PATH = ROOT / "db" / "seed" / "amd_cpu_seed.sql"

TARGET_SOCKETS = {"AM4", "AM5"}


def clock_to_mhz(value: str):
    """'Up to 5.1 GHz' -> 5100, '2 GHz' -> 2000, '3700 MHz' -> 3700, '' -> None"""
    m = re.search(r"([\d.]+)\s*(GHz|MHz)", value, re.IGNORECASE)
    if not m:
        return None
    num = float(m.group(1))
    return int(round(num * 1000)) if m.group(2).lower() == "ghz" else int(round(num))


def tdp_to_watt(value: str):
    """'65W' -> 65, '' -> None"""
    m = re.search(r"([\d.]+)\s*W", value)
    return int(float(m.group(1))) if m else None


def to_year(value: str):
    """'3/2/2026' -> 2026, '' -> None"""
    m = re.search(r"(19|20)\d{2}", value)
    return int(m.group(0)) if m else None


def to_int(value: str):
    value = value.strip()
    return int(value) if value else None


def to_has_igpu(graphics_model: str):
    """공란 -> None(정보 없음), 'Discrete Graphics Card Required' -> False, 그 외 -> True"""
    g = graphics_model.strip()
    if not g:
        return None
    return "discrete graphics card required" not in g.lower()


def normalize_model_name(name: str) -> str:
    """™/® 제거, 'AMD ' 접두어 제거, 공백 정리. 원형은 canonical_name에 보존."""
    n = name.replace("™", "").replace("®", "")
    n = re.sub(r"^AMD\s+", "", n.strip())
    return re.sub(r"\s+", " ", n).strip()


def sql_str(value):
    if value is None:
        return "NULL"
    return "'" + str(value).replace("'", "''") + "'"


def sql_num(value):
    return "NULL" if value is None else str(value)


def sql_bool(value):
    if value is None:
        return "NULL"
    return "TRUE" if value else "FALSE"


def parse_rows():
    rows = []
    with open(CSV_PATH, encoding="utf-8-sig", newline="") as f:
        for raw in csv.DictReader(f):
            socket = raw["CPU Socket"].strip()
            if socket not in TARGET_SOCKETS:
                continue
            canonical = re.sub(r"\s+", " ", raw["Name"].strip())
            rows.append({
                "canonical_name": canonical,
                "model_name": normalize_model_name(canonical),
                "release_year": to_year(raw["Launch Date"]),
                "socket": socket,
                "core_count": to_int(raw["# of CPU Cores"]),
                "thread_count": to_int(raw["# of Threads"]),
                "base_clock_mhz": clock_to_mhz(raw["Base Clock"]),
                "boost_clock_mhz": clock_to_mhz(raw["Max. Boost Clock"]),
                "tdp_watt": tdp_to_watt(raw["Default TDP"]),
                "has_igpu": to_has_igpu(raw["Graphics Model"]),
            })
    return rows


def check_duplicates(rows):
    seen = {}
    dups = []
    for r in rows:
        key = ("AMD", r["model_name"])
        if key in seen:
            dups.append(r["model_name"])
        seen[key] = True
    if dups:
        sys.exit(f"ERROR: uk_part(manufacturer, model_name) 중복 {len(dups)}건: {dups}")


def emit_sql(rows) -> str:
    lines = [
        "-- AMD 데스크톱 CPU 시드 (AM4/AM5)",
        "-- generated by scripts/generate_amd_seed.py — 직접 수정하지 말 것",
        f"-- source: datasource/{CSV_PATH.name}, {len(rows)} rows",
        "",
        "USE parts_catalog;",
        "",
    ]
    for r in rows:
        lines.append(
            "INSERT INTO part (category, manufacturer, model_name, canonical_name, release_year)\n"
            f"VALUES ('CPU', 'AMD', {sql_str(r['model_name'])}, {sql_str(r['canonical_name'])}, {sql_num(r['release_year'])});"
        )
        lines.append(
            "INSERT INTO cpu_spec (part_id, socket, core_count, thread_count, base_clock_mhz, boost_clock_mhz, tdp_watt, has_igpu)\n"
            f"VALUES (LAST_INSERT_ID(), {sql_str(r['socket'])}, {sql_num(r['core_count'])}, {sql_num(r['thread_count'])}, "
            f"{sql_num(r['base_clock_mhz'])}, {sql_num(r['boost_clock_mhz'])}, {sql_num(r['tdp_watt'])}, {sql_bool(r['has_igpu'])});"
        )
        lines.append("")
    return "\n".join(lines)


def verify_sqlite(sql: str):
    """생성된 SQL을 SQLite 문법으로 치환해 인메모리 적재 + 실전 쿼리 확인."""
    conn = sqlite3.connect(":memory:")
    conn.executescript("""
        CREATE TABLE part (
            part_id INTEGER PRIMARY KEY AUTOINCREMENT,
            category TEXT NOT NULL, manufacturer TEXT NOT NULL,
            model_name TEXT NOT NULL, canonical_name TEXT NOT NULL,
            release_year INTEGER,
            UNIQUE (manufacturer, model_name)
        );
        CREATE TABLE cpu_spec (
            part_id INTEGER PRIMARY KEY REFERENCES part(part_id),
            socket TEXT NOT NULL, core_count INTEGER NOT NULL,
            thread_count INTEGER, base_clock_mhz INTEGER,
            boost_clock_mhz INTEGER, tdp_watt INTEGER, has_igpu BOOLEAN
        );
    """)
    body = sql.replace("USE parts_catalog;", "").replace("LAST_INSERT_ID()", "last_insert_rowid()")
    conn.executescript(body)

    parts = conn.execute("SELECT COUNT(*) FROM part").fetchone()[0]
    specs = conn.execute("SELECT COUNT(*) FROM cpu_spec").fetchone()[0]
    sample = conn.execute("""
        SELECT p.model_name, c.core_count, c.tdp_watt
        FROM part p JOIN cpu_spec c ON c.part_id = p.part_id
        WHERE c.socket = 'AM5' AND c.core_count >= 8 AND c.tdp_watt <= 105
        ORDER BY p.model_name LIMIT 5
    """).fetchall()
    conn.close()
    print(f"[verify] SQLite 적재 OK: part {parts} / cpu_spec {specs}")
    print(f"[verify] 실전 쿼리 (AM5, 8코어+, 105W-) 상위 5건: {sample}")


def main():
    rows = parse_rows()
    check_duplicates(rows)

    by_socket = {}
    for r in rows:
        by_socket[r["socket"]] = by_socket.get(r["socket"], 0) + 1
    years = [r["release_year"] for r in rows if r["release_year"]]
    print(f"필터 결과: {len(rows)}건 ({', '.join(f'{k} {v}' for k, v in sorted(by_socket.items()))})")
    print(f"release_year 범위: {min(years)}~{max(years)} (NULL {len(rows) - len(years)}건)")
    print(f"thread_count NULL: {sum(1 for r in rows if r['thread_count'] is None)}건")

    sql = emit_sql(rows)
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(sql, encoding="utf-8")
    print(f"생성: {OUT_PATH.relative_to(ROOT)}")

    if "--verify" in sys.argv:
        verify_sqlite(sql)


if __name__ == "__main__":
    main()
